title: KITs開発者ブログ
description: >-
  これはJekyllで作成されたブログです。
baseurl: "" # プロジェクトページの場合はリポジトリ名
url: "https://blog.kits-tools.net" # GitHubページのURL
theme: minima # デフォルトのテーマを使用

# CSSファイルの指定
sass:
  style: compressed

category_dir: categories

collections:
  categories:
    output: true
    permalink: /categories/:name/

plugins:
  - jekyll-sitemap

